# base type (os)
FROM python:slim

# modifications

# configuration

# init
# CMD becomes ENTRYPOINT's argument
# so final command becomes : /bin/bash -c "echo hello world"
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["echo hello world"]
